import Link from "next/link";
import { notFound } from "next/navigation";
import { requireUser } from "@/lib/user-auth";
import { getOrder } from "@/lib/order-data";
import Navbar from "@/components/Navbar";
import OrderStatusProgress from "@/components/OrderStatusProgress";

export default async function OrderPage({ params }: { params: Promise<{ id: string }> }) {
  const id = Number((await params).id); if (!Number.isInteger(id) || id <= 0) notFound();
  const { supabase, user } = await requireUser(`/orders/${id}`);
  const order = await getOrder(supabase, id, user.id); if (!order) notFound();
  const address = Array.isArray(order.addresses) ? order.addresses[0] : order.addresses;
  return <><Navbar /><main className="min-h-screen bg-[#FAFAFA] pt-24 text-gray-900"><section className="mx-auto max-w-5xl px-6 py-16"><Link href="/orders" className="mb-6 inline-flex items-center text-sm font-semibold text-gray-600 transition hover:text-[#9a7613]">← Retour à mes commandes</Link><p className="text-sm font-semibold uppercase tracking-[0.35em] text-[#D4AF37]">Commande #{order.id}</p><h1 className="mt-3 text-4xl font-bold">Détail de la commande</h1><div className="mt-8 rounded-[24px] border border-gray-200 bg-white p-6 shadow-sm"><OrderStatusProgress status={order.status} /></div><div className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><div className="space-y-4">{order.order_items?.map((item) => <article key={item.id} className="rounded-[24px] border border-gray-200 bg-white p-6"><h2 className="text-xl font-semibold">{item.snapshot?.product_name ?? `Produit #${item.product_id}`}</h2><p className="mt-2 text-sm text-gray-600">{item.snapshot?.shape} · {item.snapshot?.size} · {item.snapshot?.flavor} · {item.snapshot?.color}</p>{item.snapshot?.custom_text ? <p className="mt-2 text-sm">Texte : {item.snapshot.custom_text}</p> : null}{item.snapshot?.instructions ? <p className="mt-2 text-sm">Instructions : {item.snapshot.instructions}</p> : null}{item.snapshot?.image_url ? <a href={item.snapshot.image_url} target="_blank" rel="noreferrer" className="mt-2 inline-block text-sm font-semibold text-[#D4AF37]">Image de référence</a> : null}<p className="mt-4 font-semibold">{item.quantity} × {Number(item.price)} DH</p></article>)}</div><aside className="h-fit rounded-[24px] border border-gray-200 bg-white p-6"><p>Paiement : <b>{order.payment_method === "card" ? "Carte" : "À la livraison"}</b></p>{address ? <div className="mt-5 border-t pt-5"><b>Livraison</b><p className="mt-2 text-sm">{address.full_name}<br />{address.address}<br />{address.city} {address.postal_code}<br />{address.phone}</p></div> : null}<p className="mt-5 border-t pt-5 text-xl font-semibold">Total : <span className="text-[#D4AF37]">{Number(order.total_price)} DH</span></p></aside></div></section></main></>;
}
