create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) > 0),
  slug text not null unique check (slug = lower(slug) and slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  description text not null default '',
  price numeric(10, 2) not null check (price >= 0),
  image text not null,
  category text not null check (category in ('Anniversaire', 'Mariage', 'Baby Shower', 'Graduation', 'Saint-Valentin')),
  stock integer not null default 0 check (stock >= 0),
  featured boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists products_active_category_idx on public.products (category, id) where active = true;
create index if not exists products_featured_idx on public.products (id) where active = true and featured = true;

create or replace function public.set_products_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

drop trigger if exists set_products_updated_at on public.products;
create trigger set_products_updated_at
  before update on public.products
  for each row execute procedure public.set_products_updated_at();

alter table public.products enable row level security;

drop policy if exists "Public can view active products" on public.products;
create policy "Public can view active products"
  on public.products for select
  using (active = true);

insert into public.products (name, slug, description, price, image, category, stock, featured, active)
values
  ('Royal Wedding Cake', 'royal-wedding-cake', 'Un gâteau de mariage raffiné aux finitions élégantes, conçu pour une célébration inoubliable.', 450, '/images/products/cake1.jpg', 'Mariage', 12, true, true),
  ('Luxury Birthday Cake', 'luxury-birthday-cake', 'Un gâteau d''anniversaire premium, généreux et entièrement personnalisable.', 350, '/images/products/cake2.jpg', 'Anniversaire', 20, true, true),
  ('Baby Shower Cake', 'baby-shower-cake', 'Une création douce et délicate pour célébrer l''arrivée de bébé.', 400, '/images/products/cake3.jpg', 'Baby Shower', 15, true, true),
  ('Graduation Celebration', 'graduation-celebration', 'Un gâteau festif et raffiné pour célébrer une réussite exceptionnelle.', 380, '/images/products/cake4.jpg', 'Graduation', 16, true, true),
  ('Valentine Dream Cake', 'valentine-dream-cake', 'Une création romantique aux notes gourmandes pour la Saint-Valentin.', 320, '/images/products/cake5.jpg', 'Saint-Valentin', 18, true, true),
  ('Chocolate Deluxe', 'chocolate-deluxe', 'Un intense gâteau au chocolat préparé avec des ingrédients premium.', 300, '/images/products/cake6.jpg', 'Anniversaire', 24, false, true),
  ('Floral Elegance Cake', 'floral-elegance-cake', 'Un élégant gâteau fleuri, idéal pour un mariage ou une réception.', 420, '/images/products/cake7.jpg', 'Mariage', 10, true, true),
  ('Custom Premium Cake', 'custom-premium-cake', 'Une pièce montée sur mesure pour les plus belles célébrations.', 500, '/images/products/cake8.jpg', 'Mariage', 8, true, true),
  ('Golden Birthday Cake', 'golden-birthday-cake', 'Un gâteau doré et moderne pour un anniversaire mémorable.', 360, '/images/products/cake2.jpg', 'Anniversaire', 18, false, true),
  ('Baby Blossom Cake', 'baby-blossom-cake', 'Un gâteau fleuri aux teintes douces pour une baby shower élégante.', 390, '/images/products/cake3.jpg', 'Baby Shower', 14, false, true),
  ('Luxury Graduation Cake', 'luxury-graduation-cake', 'Une création sophistiquée pour marquer la fin d''un parcours.', 410, '/images/products/cake4.jpg', 'Graduation', 12, false, true),
  ('Velvet Love Cake', 'velvet-love-cake', 'Un red velvet romantique pour une attention pleine de douceur.', 340, '/images/products/cake5.jpg', 'Saint-Valentin', 20, false, true)
on conflict (slug) do update
set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  image = excluded.image,
  category = excluded.category,
  stock = excluded.stock,
  featured = excluded.featured,
  active = excluded.active;
